; エラーコード
DRV_NOT_FOUND         = 0   ; 存在しないドライブ文字が指定された
ILLEGAL_PATH          = 1   ; ヘンなパス
FILE_NOT_FOUND        = 2   ; そんなファイルはない
NOT_DIR               = 3   ; ディレクトリではない
FAILED_CLOSE          = 4
FAILED_OPEN           = 5
FILE_EXISTS           = 6   ; ファイルが既に存在する makef失敗など
BROKEN_FD             = 7   ; 不正なファイル記述子
DIR_NOT_EMPTY         = 8   ; ディレクトリが空でないので消せない
ILLEGAL_ATTR          = 9   ; 不正なファイル属性
ILLEGAL_ARG           = 10  ; 不正な引数

