;
; File generated by cc65 v 2.18 - Ubuntu 2.18-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.18-1"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_sprintf
	.import		_couts
	.export		_main

.segment	"RODATA"

L000F:
	.byte	$68,$65,$6C,$6C,$6F,$2C,$77,$6F,$72,$6C,$64,$20,$5B,$25,$64,$5D
	.byte	$20,$68,$65,$6C,$6C,$6F,$2C,$73,$74,$64,$69,$6F,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	ldy     #$22
	jsr     subysp
	ldx     #$00
	txa
L0019:	ldy     #$20
	jsr     staxysp
	cmp     #$05
	txa
	sbc     #$00
	bvc     L000A
	eor     #$80
L000A:	asl     a
	lda     #$00
	tax
	bcc     L0017
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #<(L000F)
	ldx     #>(L000F)
	jsr     pushax
	ldy     #$27
	jsr     pushwysp
	ldy     #$06
	jsr     _sprintf
	lda     sp
	ldx     sp+1
	jsr     _couts
	ldy     #$21
	jsr     ldaxysp
	ina
	bne     L0019
	inx
	bra     L0019
L0017:	ldy     #$22
	jmp     addysp

.endproc

