;
; File generated by cc65 v 2.16 - Ubuntu 2.16-2
;
	.fopt		compiler,"cc65 v 2.16 - Ubuntu 2.16-2"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_couts
	.export		_main

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"RODATA"

L0004:
	.byte	$41,$42,$43,$00
	.res	28,$00

.segment	"CODE"

	ldy     #$22
	jsr     subysp
	ldy     #$1F
L0005:	lda     L0004,y
	sta     (sp),y
	dey
	bpl     L0005
	jsr     decsp2
	ldx     #$00
	txa
L0019:	ldy     #$22
	jsr     staxysp
	cmp     #$05
	txa
	sbc     #$00
	bvc     L000D
	eor     #$80
L000D:	asl     a
	lda     #$00
	tax
	bcc     L0017
	jsr     ldax0sp
	jsr     _couts
	lda     #$02
	jsr     leaa0sp
	jsr     _couts
	ldy     #$23
	jsr     ldaxysp
	ina
	bne     L0019
	inx
	bra     L0019
L0017:	ldy     #$24
	jmp     addysp

.endproc

