:syscall_reg1col_table: .center, width="90%"
:syscall_reg2col_table: {syscall_reg1col_table}, cols="^1,4"

== システムコール
MIRACOSのBCOSカーネルはシステムコール（ファンクションコール）ABIを持ち、ユーザープログラムはカーネルが提供する機能をシステムコールによって利用することができます。ABIはシステムコールの呼び出し手順および各システムコール関数のシステムコール番号・引数・戻り値の定義セットから構成されます。

=== 呼び出し手順
MIRACOSのシステムコールは以下の手順で行います。

. レジスタやゼロページレジスタに引数 (パラメータ) を設定
. Xレジスタにシステムコール番号を1回左シフトした値（システムコール番号の2倍の値）を格納
. `JSR $0603` を実行

システムコールからリターンしたとき、すべてのレジスタは破壊されているか、または戻り値を格納しています。原則としてゼロページレジスタは保存されますが、一部のシステムコールは特定のゼロページレジスタを破壊、または戻り値の格納先として使用します。

---
=== `CON_IN_CHR` (1) コンソール文字入力
==== 引数
[{syscall_reg1col_table}]
|===
|なし
|===

==== 戻り値
[{syscall_reg2col_table}]
|===
|`A`
|コンソールから入力された文字
|===

==== 破壊されるレジスタ
不明

==== 機能・解説
コンソールから1文字の入力を待機し、入力内容をAレジスタに返します。

---
=== `CON_OUT_CHR` (2) コンソール文字出力
==== 引数
[{syscall_reg2col_table}]
|===
|`A`
| コンソールに出力する文字
|===

==== 戻り値
[{syscall_reg1col_table}]
|===
|なし
|===

==== 破壊されるレジスタ
不明

==== 機能・解説
Aレジスタに渡された文字がコンソールに出力されます。

---
=== `CON_RAWIN` (3) コンソール生入力
==== 引数
[{syscall_reg2col_table}]
|===
|`A`
a|動作モード

[cols="^1,12,8"]
!===
!`0`
!`BHA_CON_RAWIN_GetState`
!コンソール入力バッファの残量を取得する

!`1`
!`BHA_CON_RAWIN_NoWaitNoEcho`
!コンソール入力があれば返すがエコーしない

!`2`
!`BHA_CON_RAWIN_WaitAndNoEcho`
!コンソール入力があるまで待機して返し、エコーしない
!===
|===

==== 戻り値
[{syscall_reg2col_table}]
|===
|`A`
a|

[cols="1,1"]
!===
!`BHA_CON_RAWIN_GetState` 指定時
!コンソール入力バッファ残量

!バッファが空の場合
!`$00`

!その他の場合
!コンソールから入力された文字
!===

|`Z` フラグ
|戻り値 `A=$00` でセット
|===

==== 破壊されるレジスタ
不明

==== 機能・解説
Aレジスタで指定した動作モードに応じて、コンソール入力への低レベルアクセスを行います。

`BHA_CON_RAWIN_GetState` 指定時 (`A=0`) 、コンソール入力バッファに溜まっているバイト数が取得され、Aレジスタで返されます。さらに、バッファが空でA=0となった場合はZフラグがセットされます。

`BHA_CON_RAWIN_NoWaitNoEcho` 指定時 (`A=1`) 、

